config/routes.rb
Rails.application.routes.draw do
  resources :scores
  devise_for :users
  root 'root#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true


  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/score.rb
# frozen_string_literal: true
class Score < ApplicationRecord
  # main config ...............................................................
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :user
  # validations ...............................................................
  validates_presence_of :score_date, :username, :user_id, :points
  validates :username, presence: true, length: { minimum: 1, maximum: 255 }
  validates_numericality_of :points
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # public instance methods ...................................................
  def self.import(file_path)
    CSV.foreach(file_path.first) do |row|
      p row
      score_date, username, user_id, points = row
      score = Score.new(score_date: score_date, username: username.strip, user_id: user_id.to_i, points: points.to_i)
      p score
      score.save
      p score.errors.full_messages
    end
  end

  # protected instance methods ................................................
  # private instance methods ..................................................
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  rolify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :scores

  validates :name, presence: true, length: { maximum: 100 }
  validates :email, presence: true, uniqueness: true, length: { maximum: 100 }
  validates :username, presence: true, uniqueness: true,
            length: { maximum: 100 }
  validates :bio, length: { maximum: 160 }
  validates :url, length: { maximum: 100 }
  validates :location, length: { maximum: 100 }

  def actual_score
    points = scores.sum(:points)
    return 3126 if points >= 3126
    points
  end

  def actual_percentage
    (actual_score * 100) / 3126
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!
  load_and_authorize_resource

  def authenticate_admin!
    unless current_user.has_role? :admin
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to main_app.root_url, :alert => exception.message }
    end
  end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
  end
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
end

app/controllers/root_controller.rb
# frozen_string_literal: true

class RootController < ApplicationController
  # GET /
  def index
    @users = User.all.order(:created_at)
  end
end

app/controllers/scores_controller.rb
class ScoresController < AdminController
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all.page(params[:page])
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: 'Score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:score_date, :username, :user_id, :points)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Scoring Processing'

    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
# Cria um link para visualizar
#
# @param path [String] path de visualização
  def link_to_show(path)
    link_to path,
            class: "btn btn-info btn-sm",
            title: "Visualizar",
            style: "color: #FFF; float: none;" do
      content_tag :span, class: "fa fa-search" do
      end
    end
  end

# Cria um link para editar
#
# @param path [String] path de editar
# @param options [String] path de editar
  def link_to_edit(path, *options)
    link_to path,
            class: "btn btn-warning btn-sm",
            title: "Alterar",
            style: "color: #FFF; " do
      content_tag :span, class: "fa fa-pencil" do
        options.first[:label] if options.present? && options.first[:label]
      end

    end
  end

# Cria um link para Excluir
#
# @param path [String] path de excluir
  def link_to_remove(path)
    link_to path,
            method: "delete",
            class: "btn btn-danger btn-sm",
            title: "Excluir",
            data: { confirm: label_translate(:confirm_delete),
                    'confirm-button-text': "Confirmar",
                    'cancel-button-text': "Cancelar",
                    'confirm-button-color': "#66CD00",
                    'cancel-button-color': "#ff0000",
                    'sweet-alert-type': "warning",
            },
            style: "color: #FFF; float: none;" do
      content_tag :span, class: "fa fa-trash-o" do
      end
    end
  end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/translate_helper.rb
# frozen_string_literal: true

# Todos os métodos presentes nesse +helper+ dependem do conteúdo de config/locales
module TranslateHelper
  # Retorna um label traduzido
  #
  # @param label_name [String|Symbol] nome da label
  #
  # @return [String] label traduzido
  def label_translate(label_name)
    I18n.t("labels.#{label_name}")
  end

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Scoring Processing</a>
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <%= link_to root_path, class: 'nav-link' do %>
        <%= fa_icon 'home', text: 'Home' %>
      <% end %>
    </li>
    <% if user_signed_in? %>

      <li class="nav-item active">
        <%= link_to scores_path, class: 'nav-link' do %>
          <%= fa_icon 'medal', text: 'Pontuações' %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <% if user_signed_in? %>
        <%= link_to t('pages.sign_out'), destroy_user_session_path, method: :delete, class: 'nav-link' %>
        <%else %>
        <%= link_to t('pages.sign_in'), new_user_session_path, class: 'nav-link' %>
      <% end %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="<%= I18n.locale %>">
<head>
  <meta content="text/html; charset=utf-8" http_equiv="Content-type"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <title>
    <%= full_title(yield(:title)) %>
  </title>
  <meta content="IE=edge" http_equi="X-UA-Compatible"/>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container container-fluid">
  <%= yield %>
</div>
</body>
</html>

app/views/root/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  Ranking de pontuação dos usuários
  <% @users.each do |user| %>
    <div class="progress" style="margin-top: 10px;">
      <div class="progress-bar" role="progressbar" style="width: <%=user.actual_percentage%>%;" aria-valuemin="0"
           aria-valuemax="100">
        <%=user.username%> - <%=user.actual_score%> pontos</div>
    </div>
  <% end %>
</div>

app/views/scores/_form.html.erb
<%= simple_form_for(@score) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :score_date %>
    <%= f.input :username %>
    <%= f.association :user %>
    <%= f.input :points %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<h1>Scores</h1>
<% if can? :create, Score %>
  <%= link_to 'New Score', new_score_path, class: 'btn btn-sm btn-primary' %>
<% end %>
<table class="table">
  <thead>
  <tr>
    <th>Score date</th>
    <th>Username</th>
    <th>Points</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @scores.each do |score| %>
    <tr>
      <td><%= score.score_date.to_s_br %></td>
      <td><%= score.username %></td>
      <td><%= score.points %></td>
      <td>
        <% if can? :show, Score %>
          <%= link_to_show score_path(:id => score) %>
        <% end %>
        <% if can? :update, Score %>
          <%= link_to_edit edit_score_path(:id => score) %>
        <% end %>
        <% if can? :destroy, Score %>
          <%= link_to_remove score_path(:id => score) %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @scores %>

app/views/scores/new.html.erb
<h1>New Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Score date:</strong>
  <%= @score.score_date.to_s_br %>
</p>

<p>
  <strong>Username:</strong>
  <%= @score.username %>
</p>

<p>
  <strong>User:</strong>
  <%= @score.user.username %>
</p>

<p>
  <strong>Points:</strong>
  <%= @score.points %>
</p>
<% if can? :update, Score %>
  <%= link_to_edit edit_score_path(:id => @score) %>
<% end %>
<%= link_to 'Voltar', scores_path ,class: 'btn'%>